sudo: required
language: python
dist: trusty
python:
    - '3.5'

addons:
    apt:
        packages:
            - sshpass

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install texlive texlive-lang-french texlive-latex-extra

install:
- pip install docopt
- pip install pyyaml
- pip install jinja2

script:
- make

after_success:
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && cd out
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && tar cjvf package.tar.bz2 *
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && export SSHPASS=$DEPLOY_PASS
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sshpass -e scp package.tar.bz2 $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh


env:
  global:
  - secure: FpuZiY/+WNe7KoKtAbhqp+VPKRYmvHd5YRPy9NME/Nx+Ry9JqNRopsHDe1q5k4Fr5yEBUFeINrZ1OSuN1upvFo5uRMx9CIetoVbdVje/cejil3zo4TxgjgGpPuh+xQvsJKG5kfea/e6dZA505Nldo/65zh1X1JHV2MhOOWlAJqTNYggMCxD264sLZ88Ha4r8jbBwlsDY3UH+iejZ7Xuw4+Iypzp0RGCEIp1GfjUSD4boGYw6CGFYnTrroiBXsAJWwkvH0BY+3QAnAELb7RHGrMtHapuxJmfn1Is3ZlfKgPEk1sXosVWp1ULqS0M8BSNiCajOjUIW/CsPZh3xAacrnMYoJQS1dN5HoIrSzHq80gcmScuQQLjiu7r5wvyAp4XIsBh8H1GJa+GpvcSCYs86Kv2R2ekfkVxZSyKAYYosAHfQkZyAbiILE13Vc4udagc90r1tgyMTmEXOZ1uPI4l1O8xN4wjJ17zqQpI0OgHqSJVMQPEhjM2KrzxanF/eYG9Jd7loD0zGhAoxqf1vXbACa5YbO0sCA2bt3YJhWaPN0MPKYnI2rDyhuK4MQZmnYPA0WTpr3UIJVKu3Xl2rt3XEeZAzWCC9LX9kPISafBb8dqANzZmA6+xi3NuOM6c8aqPzZkYFgHSAtN/g0usptwdO5DoS6VEqLWMeHN4nWOau+YQ=
  - secure: sRDLQHcevUJlMnayNSWuHgkQQVL6tL4wX5zpl7PimRxhMxUUuN5fNJWG/WduPxUfDMWS1gLWSzssnxUPqB06TtFhn6dkXOA5E5nDf+I/E6JhdWG4tS7+ePOal/HtPmFMOq6m+NMigbwOg98bey6o4coVFPINAcHTp3z8ADeheGpDQo8AEqHtXONrEwR/r8kg8ZsndaeiF0TrZxl/dawWmpU5YYHKEjiWYuFboOHLI0nWWgzcBod1dSLK2+/o6wtcUYVwcFzoR21x1oVDyrMdlP0w7GZh2I461oLH4KmC+Sv9IPTOp49VzRCe7SnlwZWOTYjSHDitEIohrAgxA9trRPO0i35Amkt0C8q4bLMEaQt32PqfH+4HcpEcoqtTI2CVIauahlU10Mo7EYp2pqDg3w8gKd3EZwVtwEicNurY5UbLB19FwuzhYc/bZoGVvQnZal4SZ+f0WwBk6cOlSHCqRWmsDirsFR58xa2Kcnwps4eCB+Kua7/gHUF/J1AsezxETC3d8Op7ra5ihdak/nMhuiCMJNElkROBzbbH1meCFJFEqGOxwbmJLLPqpi3By15Bh11xZZIMlIMuS2r1Bsw8vb838EZcmooggwaMd2eOoQYiTlh4j9+k35pKw0o7vv5VLtgqIBvMk/Fv5qe39jUct6KvxmOwRDvHNcOSRA7T6c4=
  - secure: frD6oURsKXDXMBss+ChKqLMm7Sdt3t3jGyomvhFpNhOFwfk0aCCebvFLyKkSxJSlKLCK8ZigDmFDQLB8TrFNmWbyTLr+JbzMevfwtLew6ZEXXWBSF9KWkIYwyxvvY1S29Xk7yF8DFPzvHbW7b7Emhb516OdNb4PdzxjOww7zNAnriv+UNZUHTbuPVRIYaBihTG/RR8yrUbDuq8xKpOS1yjTCujPjhXD2y7+uRkctzaAPhk8lgDMTcQsyDlodHmud5qs7OMskPhydZI/j8gh8snMB74lJZevpSz1aJP/YuD2bSBnFBWEQ456YFBVY+stEEiWTU2OxcuwG7lilgMjhfXHHuV5tUJ7X64DcOI4ZvvoCJOxYu0I5HtktNcM/EKnc2zgMcJ8RXm+V452RtXJ+UgaSDLy4/l1fiRrSmWsZJhAXfrXsTpqknNoy63pdHvtcYN0NiXqn5UehbXbaefOoXGSBtaobxMWXRPfU604qJwzzbl37Hp4QP064k2PpgF0/ixKdYUgibfRkV+4U2BsIVGcw9U8q+FBHM4CmxrYjXnYu9mRdmm8j6ACf1sJ4eitmrPCW9oAfORk2q44FrmyXJ7VYMMiAMFRPvy4QihmixwUexCmUy/6wbpeRZZ7lNbyMg7Mpr0UVtZ4+fWPYnoMCQ+03Fb2aEnDnTe5MuQb6vR4=
  - secure: kF6l+N375E9PAzx6aN6+hDy/r0foHUuUFYlWoVTY+hZxwBynm3h0ykLoe1iZ9W/YfZGggOPBcnABO47Ic/hrTYxPneebWwC5eaJWO0bAGdcAeyiNwKqsTnU9uP07kffgtWi4tD19yIjhXdpDrJkoVcLjBJ0uGGGUad0Cr1uHOaE/fSwVpAU4wyVW1L7UFvB4a4W4Lrv4thbo4iFuojXpPZSrFPJYmu2PVkKA+nFpA8DPk30npiGRfehCXf8DKYDw7ihXLIKZB6C+yHbkFmp2PgSK2BK+xyDiBONf8BYWKrpmjo+Gr7t4Dp0KnNlumF44jf9pibt6NH4x3TocjeUY6o2y1F18xMK6E+CiKGVKK9JHX9S8ds/bjDp3DscQe/B7/7lycn1NCKKzr1xprJOAKM/kP5ofj95FTfTPpo1NIeUVY3HjAxSJkofS5TEx85GWaf4r3MusZIAFdeTvxwDszkUFuN7r1tWTSFX52xAAdthCQu+xov0bkGy53m5/R3rP6wILWmW9nUtosSPiQHNt/iVjMHJoOXdfc242uEfMgq+YcV/WdSV7totFsQy1wfvqXVfNMvclJTtngML3k7B3piIH7+rRu0tatH4h/c623WveXAG/uGXqWvf+77X5hxCzAkxOzDdXDgZDTwU6yxXY4h/YQKvw4LiZSK9I5g7mh1E=
