sudo: required
language: python
dist: trusty
python:
    - '3.5'

addons:
    apt:
        packages:
            - sshpass

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install texlive texlive-lang-french texlive-latex-extra

install:
    - pip install docopt
    - pip install pyyaml
    - pip install jinja2

script:
    - make

after_success:
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && cd out
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ssh-keygen -R $DEPLOY_HOST
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && export SSHPASS=$DEPLOY_PASS
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sshpass -e scp -r -o stricthostkeychecking=no * $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

env:
  global:
     - secure: "Fl2FbdqHTWjgJcbzFprby5GfGtkU6Jv5ybAGd+kMWDy3OTQ4p8HMtyG9qR3IsJjhYun4ZnVxO7qzVCGQvB9qvLv9NZjhR0ytr58H7DuxaAfdzxZLUZNzhQoFkOSZZ63NHIYgpKYv8U5KeuvBDwKFnT3bf4EZl2JJS4bAiAVU8uvAYXt4oQG/GMlk+nN1iC4mQQ27fUSVU+bFc/cZ1g6CP1Fj+6pqbp9D/PA89Ls8tT5rGooReTeBr33Nx2viSF7Exc18J6REP55XTZJ9ZowO7OcaVk+chsfIFQHDObvlgtir5hdMsRNo1SCDauBrgl/BeCbbTUfNhU7x4heFnVe5XPqv5feCRq5CQe5S8UFhIhDPE0A3k2iUVx0i0nIPYiUzqWoJ3Hl2zKA8jZTn9rXQa/Eyr5WXSGY9kNkLOhD+XY48bm71lz+m4kx19g0OA1cozAfyFLn4svXu2TCzXyb745+1kqN/WRPlhexTltqQCpwrTENAkoCcT6Igcj3zoBDpZK+MCkTvQkaDIPoGhnXm3JILPbQLjhYEYoszPbT5+z10+h+4P2bJiSrDQka8vfcZCOjL3vr+B4jbkJNqTpaHjIYDW8gWfK1yvlebcqmAPLv+W9Vbi2/5nbmyi1y4fZsdauGaR1E96J7kWNPSdNbfvrHh5blr6rnHFwADbVlZPRw="
     - secure: "qFp23XyxyAMrOkiAx12fR1sEFj2SbCdCAVAIShXmXwpJE9cIMgpYlBwwaNaqnCY1wn8jK5wjNZG6HtX7xr2OBMZgC0ark0l82wsdevNZ5aj5SnTqkJJ/xGP/0DIYMUUAcCLxIEkRRdbrmz7STHnMZulBS1DqH+fo6mQx/DbTE3b6UiWKnLgK95OVXPVk976M/ao0ofOdc9kW2wizwnHZ67e2hibA5+VKOuqMunwkGXMaLbk9e3euhALg2JgG+9Vfn8R7EJX/MtGcrH1R3p0H8TzMJp4rMmteXvP11ixcr32MkOjsZf1dxT2nMGVQLB8F2NaSgCkcEONMj4cFgSMCUSGqwsVX5OT2YEjufLvzKkBoqm+jPEdgJu/+zyxg+cHOf6JJ1swlzDCXckkdGfbnGmutc9CeCXmnjq881BGW890wbYtDlK38XK0aHvCbU7euP8zGQMTV42ZoGv7YSIt713XQ7towFV2Bnd7cBYjVzg6rt7JKBVB/l9DCMx+sBOBgbkXH6IsW5ZbOjIkxBrvqUfFtdfeUVCFSgAJqWa0O/D7f3IEbjlcoEyiM7F0pecrG3qpvV1XDHJpY5Mo/jjnAWGls+EOTj5rliDXD22wi48teMym8u5XosdACELSG11ql7bhEMOAviw3h55j1dkFzDDOIb9gHTU/j6xBq83bDNVw="
     - secure: "VcnGbphkYKtkLsMhndLSdWCz2olKTHgudmij6naDlVNV34THSP65CTMX6TuhtSJm6qqqmWsoyDKkkMSwwe5P+ZL9IiGdTE2y9KONTwhsFV3rQzqMsqVwL7SOBG1vURNCkSeZXelaAL1Kqv0vfpQ5XRJ31Gn+0ITHQv3gSP3kzW03Sb4UWdmdJ2KZQneXEWNvm493vuxqC3JmAvXdSFa9KI/CA/uNNzQcmXUBkJO+s62ffULg74n7c4lf17fxWmfl6PDs9zahidKhuNeQ7sDOrgtHPoEouCq3CAncV+0nsq5Au+xQnIDRfMtB9dIP6Y1CgfIufUT9wW7/j9HFHxCXIkuXfL6xI5psuO18MwRUXI8ADpzDLe3I6ZA10Mbb0wm/whuzGEZ/GsbgkAIOLPQj6VP/pibLwmKG/8oOC6JXhp9JSkeuJwQAOuyWUTZqEcIBoi/2vakKHk4WZf49dRe05eKGKIzr0EvsMue41rzFjCzV/+KMGDBKSv0tTZAHJeZHHB2/PGSqx/Si2izELnUXmNq8rsXRxdRF3C0r3kSRonRd7oF5Vr7hGWbGpMrSUOJxFK8Mkx1tXQjG61MJmrkSyZmtq/r61ekAwXA5JkrvwPf3CvfFxO6Ug/U3Bw0ZzXTEubXaXRrL7Kd7SCOCcn8FTIfeJf1rkXAopUaJ750/+g0="
